"""add content column

Revision ID: 0745f7637a90
Revises: 
Create Date: 2026-07-09 20:39:10.741322

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0745f7637a90'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('content', sa.String(), nullable=True))
    op.alter_column('documents', 'workspace_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('documents', 'workspace_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('documents', 'content')
    # ### end Alembic commands ###
