"""add uploaded_by

Revision ID: 799d7bd4fa89
Revises: d96ae050528b
Create Date: 2026-08-10 23:02:55.880449

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '799d7bd4fa89'
down_revision: Union[str, Sequence[str], None] = 'd96ae050528b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('uploaded_by', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('documents', 'uploaded_by')
    # ### end Alembic commands ###
