"""add bookmarks table

Revision ID: d96ae050528b
Revises: 0745f7637a90
Create Date: 2026-08-08 14:12:47.800543

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd96ae050528b'
down_revision: Union[str, Sequence[str], None] = '0745f7637a90'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bookmarks', sa.Column('message_id', sa.Integer(), nullable=False))
    op.drop_constraint(op.f('bookmarks_workspace_id_fkey'), 'bookmarks', type_='foreignkey')
    op.create_foreign_key(None, 'bookmarks', 'messages', ['message_id'], ['id'], ondelete='CASCADE')
    op.drop_column('bookmarks', 'answer')
    op.drop_column('bookmarks', 'question')
    op.drop_column('bookmarks', 'workspace_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bookmarks', sa.Column('workspace_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('bookmarks', sa.Column('question', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('bookmarks', sa.Column('answer', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'bookmarks', type_='foreignkey')
    op.create_foreign_key(op.f('bookmarks_workspace_id_fkey'), 'bookmarks', 'workspaces', ['workspace_id'], ['id'])
    op.drop_column('bookmarks', 'message_id')
    # ### end Alembic commands ###
